### PR TITLE
fixed some markdown-formatting

### PR DESCRIPTION
**Pull request by ridicolos**
Fixed some markdown-formatting-issues inside the README and adjusted the headline-levels.

This does mostly comply with the rules defined here: <https://github.com/markdownlint/markdownlint>
The only rule which doesn't apply is `MD013 Line length`. With a maximal default line length of 80 characters.

```output
README.md:7:81 MD013/line-length Line length [Expected: 80; Actual: 88]
README.md:11:81 MD013/line-length Line length [Expected: 80; Actual: 674]
README.md:87:81 MD013/line-length Line length [Expected: 80; Actual: 200]
README.md:89:81 MD013/line-length Line length [Expected: 80; Actual: 305]
README.md:93:81 MD013/line-length Line length [Expected: 80; Actual: 304]
README.md:95:81 MD013/line-length Line length [Expected: 80; Actual: 244]
README.md:99:81 MD013/line-length Line length [Expected: 80; Actual: 168]
README.md:101:81 MD013/line-length Line length [Expected: 80; Actual: 171]
README.md:105:81 MD013/line-length Line length [Expected: 80; Actual: 251]
README.md:109:81 MD013/line-length Line length [Expected: 80; Actual: 261]
README.md:113:81 MD013/line-length Line length [Expected: 80; Actual: 298]
README.md:117:81 MD013/line-length Line length [Expected: 80; Actual: 284]
README.md:145:81 MD013/line-length Line length [Expected: 80; Actual: 305]
README.md:147:81 MD013/line-length Line length [Expected: 80; Actual: 137]
README.md:148:81 MD013/line-length Line length [Expected: 80; Actual: 285]
README.md:165:81 MD013/line-length Line length [Expected: 80; Actual: 135]
README.md:167:81 MD013/line-length Line length [Expected: 80; Actual: 239]
README.md:172:81 MD013/line-length Line length [Expected: 80; Actual: 94]
README.md:180:81 MD013/line-length Line length [Expected: 80; Actual: 155]
README.md:184:81 MD013/line-length Line length [Expected: 80; Actual: 242]
```

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Fixes formatting, thanks!

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Review by MalloD12 — APPROVED** [review]
Approved.

## Review and testing results:

Formatting fixes looks good to me according to Markdownlint [rules](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md ). 

### Things to be aware of:
- None

### Things to worry about:
- None

**Review by filipelautert — APPROVED** [review]
Documentation updates are welcome!

**Comment by filipelautert** [comment]
@jnewton03 another one that could me merged in your merge batch.

**Pull request merged**
