### PR TITLE
fixes #140: allow to run liquibase history command

### LINKED ISSUE #140: Liquibase History command fails assuming it is an OS command
When testing Liquibase Docker image with GitHub Actions, it appears that unlike other commands, the Liquibase History command fails.
It looks like the Liquibase History command is logically being considered as a Linux OS history command first before being considered as a Liquibase command.

**Steps to reproduce**
1. Set a GitHub workflow with Liquibase Docker image and a job with the history command.
```
  Build_Job:
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps:
    - uses: actions/checkout@v2
    
    - name: Running the history command
      uses: docker://liquibase/liquibase:snowflake
      with:
        args: history
````

2. Run the workflow.

**Actual results**
`
Run docker://liquibase/liquibase:snowflake
/usr/bin/docker run --name liquibaseliquibasesnowflake_963cf4 --label e28490 --workdir /github/workspace --rm -e LB_VERSION -e ***_PRO_LICENSE_KEY -e ***_COMMAND_URL -e ***_COMMAND_USERNAME -e ***_COMMAND_PASSWORD -e ***_COMMAND_CHANGELOG_FILE -e ***_HUB_API_KEY -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Snowflake/Snowflake":"/github/workspace" liquibase/liquibase:snowflake history
/liquibase/docker-entrypoint.sh: line 10: exec: history: not found
`

### PR DESCRIPTION
**Pull request by jgarec**
Hi, 

This PR allows to override default entry point behavior.
If first argument is "history" then it should not be considered as a system command but as history liquibase command.

**Tests :**

- No argument : 

```
./docker-entrypoint.sh
Could not find defaults file /liquibase/liquibase.docker.properties
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
....
```

- ls argument

```
./docker-entrypoint.sh ls
Dockerfile                      LICENSE                         README.md                       docker-entrypoint.sh            examples                        liquibase.docker.properties     pom.xml
```

- history argument
```
./docker-entrypoint.sh history --help
Could not find defaults file /liquibase/liquibase.docker.properties
List all deployed changesets and their deployment ID

Usage: liquibase history [OPTIONS]

      --changelog-file=PARAM
                         The root changelog
                         (liquibase.command.changelogFile OR liquibase.command.
                           history.changelogFile)
                         (LIQUIBASE_COMMAND_CHANGELOG_FILE OR
                           LIQUIBASE_COMMAND_HISTORY_CHANGELOG_FILE)
                         [deprecated: --changelogFile]
```

### CODE REVIEW

**Comment by nvoxland** [comment]
Initial review:

I see how those overlaps will be a problem. This fixes it for history, but I wonder if there is an easy way to check for any liquibase commands that are also commands in the OS? 

Probably not right now, but something to consider for the future?

Things to be aware of:
- Nothing

Things to worry about:
- Nothing

**Review by filipelautert — APPROVED** [review]

**Comment by filipelautert** [comment]
@jnewton03 I tested locally and it works. If you think it's fine could you merge it? 
Thanks!

**Comment by jnewton03** [comment]
> @jnewton03 I tested locally and it works. If you think it's fine could you merge it? Thanks!

Hi @filipelautert I agree with @nvoxland that we probably need to make sure the fix works for all potential OS-level arguments.  Will take a look.

**Comment by jnewton03** [comment]
@filipelautert I looked into this today and I agree that his should fix the issue.  Approved.

**Pull request merged**
