### PR TITLE
Added Snowflake extension jar to docker image.

### PR DESCRIPTION
**Pull request by lgadawski**
Added liquibase snowflake extension which is required for snowflake JDBC jar to connect to Snowflake instance.

### CODE REVIEW

**Comment by lgadawski** [comment]
How can I found details of failed tests in Docker Cloud? When I click hash id I got 404.

**Comment by lgadawski** [comment]
@r2liquibase, could you help me to get dockercloud-stage build details?

**Comment by r2liquibase** [comment]
https://gist.github.com/r2liquibase/d92c635941c8030a0580ed30ce8e430b

**Comment by r2liquibase** [comment]
You can replicate this with `docker build .` in the root of the repos.

**Comment by lgadawski** [comment]
Thanks, I was able to replicate and fix the problem. Now hopefully pipeline will succeed.

**Comment by lgadawski** [comment]
Also to make you sure that added jar is need I'm referring liquibase doc - https://docs.liquibase.com/workflows/database-setup-tutorials/snowflake.html

**Comment by r2liquibase** [comment]
Pretty sure we do reference the Snowflake extension on that page. Do we not?

**Comment by r2liquibase** [comment]
Hey, @lgadawski , do you mind if we take this conversation to Discord? https://discord.gg/9yBwMtj This is the Liquibase community discord. Want to get your thoughts on some changes we're planning to make to the Docker container. I think this is a good opportunity to do that for Snowflake and test it.

Let me know! Username there is the same as GH for me. Hit me up! Thanks!!!!

**Comment by r2liquibase** [comment]
Sorry we couldn't connect today @lgadawski ! What are your thoughts on this instead?

https://github.com/liquibase/docker/pull/64

**Comment by liquibase-docker** [comment]
Hi, @lgadawski ! Check this out: `docker run liquibase/liquibase:snowflake`

**Pull request closed without merging**
