### PR TITLE
feat: build and push liquibase docker images via GH

### LINKED ISSUE #126: Arm64 arch not usable (Apple M1 chips)
Due to a qemu upstream bug, this container is not usable in arm64 archs with x86 emulation, with the following outcome:

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
``` 

Building this image locally in an arm64 machine works perfectly, without any major compatibility issues.

There's not much hopes of getting the bug fixed, with most support being:

> Please encourage the author of this container to supply an arm64 or multi-arch image, not just an Intel one

Please consider building this image in arm64 architectures in the near future. Especially now that M1 looks to be the mainstream Apple platform for new machines.

### PR DESCRIPTION
**Pull request by sfat**
- Support for both amd64 and arm64 platforms
closes #126

### CODE REVIEW

**Comment by sfat** [comment]
did a test with a new docker hub dummy repository, seems to be working fine: https://hub.docker.com/r/sfat/test-liquibase-docker-image-push/tags.

The only required things needed is to add two new repository env secrets:
* DOCKERHUB_USERNAME
* DOCKERHUB_TOKEN

**Comment by jnewton03** [comment]
@nvoxland ⬆️

**Comment by nvoxland** [comment]
I think the changes make sense to me. The proof will be in doing a release :)

Thanks, @sfat !

**Comment by sfat** [comment]
> I think the changes make sense to me. The proof will be in doing a release :)
> 
> Thanks, @sfat !

I did do a test before doing the PR (pushing on my own docker hub account)
https://github.com/sfat/liquibase-docker/actions/runs/4111340307

**Comment by jnewton03** [comment]
I have added the secrets for `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.  I have also disabled the autobuild jobs within Docker Hub.  I *think* this is okay to merge, @nvoxland @filipelautert.

**Review by jnewton03 — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
All seems good, thanks for the contribution @sfat  !
Now let's release it and see those :ship: running on arm64 .

**Comment by jnewton03** [comment]
Merged.  Next release will be via GHA and should generate Arm64 images.  Thank you so much @sfat !

**Pull request merged**
