### PR TITLE
DAT-10956 Docker Native Executors Examples

### PR DESCRIPTION
**Pull request by jnewton03**
- add section to README on native executors
- create /examples directory
- create subdirectories for sqlplus, sqlcmd, and psql
- provide example Dockerfiles for each of the above

### CODE REVIEW

**Review by mcred — APPROVED** [review]

**Review by StevenMassaro — APPROVED** [review]

**Review by molivasdat — COMMENTED** [review]
For mysql, are we adding the native executor.  If not we need to update the readme or not include it.

**Comment by jnewton03** [comment]
> For mysql, are we adding the native executor. If not we need to update the readme or not include it.

@molivasdat the example that is there currently is for adding the mysql driver since we can't bundle it.  I can add an example for the mysql native executors.

**Comment by jnewton03** [comment]
@molivasdat I removed mysql from the `examples` folder since the rest are native executor examples.  In the README we have a separate section for `Native Executors` vs `MySQL` since the latter calls out that we cannot ship the driver and gives example of how to add them.  Does that work?

**Review by molivasdat — APPROVED** [review]
Happy to have the mysql Dockerfile, just explaining in the readme that it is not a native but the driver is installed in that one instead works too.

**Pull request merged**
