### PR TITLE
add aws ssm agent per https://github.com/liquibase/docker/issues/127

### PR DESCRIPTION
**Pull request by ap-liquibase**

### CODE REVIEW

**Comment by nvoxland** [comment]
@ap-liquibase and @molivasdat Is this PR still needed/wanted?

**Comment by nvoxland** [comment]
Given recent discussions on how the docker containers should be kept slim, this is probably not something we want?

**Comment by jnewton03** [comment]
In general I prefer not to add anything to the base liquibase docker image, but rather have people extend the image based on their needs.  That's what we've done for things like the AWS CLI, drivers, etc.  Thoughts @mcred ?

**Comment by r2liquibase** [comment]
I'm the one that started the issue. I say we close this and the orig issue. We should use the `FROM liquibase/liquibase` directive in a new file and add it there.

**Pull request closed without merging**
