### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dhwanitsshah**
- Added bash support
- Added --no-cache to apk calls to keep the container/image size as small as possible

### CODE REVIEW

**Comment by dhwanitsshah** [comment]
This fixes the current issue with liquibase:latest docker image. Basically resolved the issue reported here: https://github.com/liquibase/docker/issues/13

**Comment by r2liquibase** [comment]
Hi, @dhwanitsshah ! We've chanted to `openjdk:11-jre-slim-buster` because `openjdk:8-jre-alpine` is not supported in Docker Official Images. We're attempting to get this image as an official image so users can run `docker run liquibase`. What do you think of that?

**Comment by dhwanitsshah** [comment]
Okay thanks for the info @r2liquibase - I would also vote in favour of us using the base image which is present in list of Docker official images.

**Comment by r2liquibase** [comment]
thanks!

**Comment by r2liquibase** [comment]
We now have tests passing for the Official Docker Image PR. https://github.com/docker-library/official-images/pull/8409. If this is valuable to you, would love your thoughts on the PR. Thanks!

**Pull request closed without merging**
