### PR TITLE
Fix issue 33. Set correct permissions for docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by rk13**
This should fix the problem with the latest Docker build reported in https://github.com/liquibase/docker/issues/33

### CODE REVIEW

**Comment by ramonberrutti** [comment]
LGTM

**Comment by r2liquibase** [comment]
Thank you!!!

Hi, @jgkoops! What do you think?

**Comment by jgkoops** [comment]
OK, always better to have scripts run w/ the designated user

**Review by jgkoops — APPROVED** [review]
always better to have scripts run w/ the designated user

**Comment by jgkoops** [comment]
Sorry about the close

**Pull request merged**
