### PR TITLE
DAT-16949: Publish to Marketplace

### PR DESCRIPTION
**Pull request by sayaliM0412**
feat: `.github/workflows/create-release.yml`: Publish to marketplace ECR

### CODE REVIEW

**Comment by jandroav** [comment]
is this still valid @sayaliM0412 ?

**Comment by sayaliM0412** [comment]
> is this still valid @sayaliM0412 ?

Just was waiting on a reply from Kevin last time I checked:
https://datical.atlassian.net/browse/DAT-16949

**Comment by jnewton03** [comment]
> > is this still valid @sayaliM0412 ?
> 
> Just was waiting on a reply from Kevin last time I checked: https://datical.atlassian.net/browse/DAT-16949

@sayaliM0412 can you please confirm if this is still needed?

**Comment by sayaliM0412** [comment]
> > > is this still valid @sayaliM0412 ?
> > 
> > 
> > Just was waiting on a reply from Kevin last time I checked: https://datical.atlassian.net/browse/DAT-16949
> 
> @sayaliM0412 can you please confirm if this is still needed?

Question asked: https://datical.atlassian.net/browse/DAT-16949?focusedCommentId=142011

**Comment by sayaliM0412** [comment]
closing the PR based comment made by @kevin-atx :https://datical.atlassian.net/browse/DAT-16949?focusedCommentId=143876. Will open it again if needed

**Pull request closed without merging**
