### PR TITLE
Docker config changes

### PR DESCRIPTION
**Pull request by nvoxland**
I made a few changes:

1. Removed separate 3.10.x dockerfile setup in favor of branches

I also deleted most of the docker build configs in favor of (currently) just building off release tags. Eventually we will want to build "latest" off main as well, but we'll make sure the new version works first.

If we ever need to do a patch release off a previous build, we can check out the previous tag as a branch, make the changes, and tag that new branch.

2. Added support for LIQUIBASE_ environment variables

You can now specify LIQUIBASE_* environment variables which are used as liquibase CLI arguments. 

So instead of specifying `--url=X` you can set `-e LIQUIBASE_ENV=x`

3. There are now /liquibase/classpath and /liquibase/changelogs volumes which liquibase is auto-set to add to the classpath.

That means you simply have to mount your changelog root to /liquibase/changelogs and it will work. No need to set the classpath

### CODE REVIEW

**Comment by r2liquibase** [comment]
Hi, @jgkoops ! What are your thoughts? @nvoxland wanted to add some sanity to how I was managing tags. He wants to use branches and he is correct!

**Comment by jgkoops** [comment]
Hi, I'm very much in favor of using branches, that  the way to go!
I'm not too happy with the way the environment variables are handled because of: 
1. the use of bash and hence the introduction bashisms. We had problems when we moved from an older version of Liquibase that did use bash as well (so we used it) an then there was the switch to sh and our scripts broke.
2. the copying of the CLI input to the liquibase.properties file. The CLI input is often very sensitive (username/password, LiquibasePro key) and I'd rather not have that stored in a docker container

**Comment by nvoxland** [comment]
Thanks for taking the time to look at it.

Yes, the script changes do require bash (and even newer versions of bash) but I figured that since that file is always running inside a known docker image with a known version of bash that would be fine. What problems did you hit before? 

That is a good point on the storing of values in the liquibase.properties file.  I tend to think of containers are transient, but they aren't always. We are planning on adding support for environment variables within Liquibase in an upcoming release, but was trying to get it into the Docker version a bit sooner since that is an even more common pattern there.

I could add an `rm liquibase.properties` call at the end of docker-endpoint.sh. That would keep it from sticking around, but it will still be there during the Liquibase run. Do you feel like that would be good enough until we can get better support into main liquibase? Or safest to just keep it out until we can better support it officially?

**Comment by r2liquibase** [comment]
How does @nvoxland proposal sound @jgkoops ? Thank you!!!

**Comment by jgkoops** [comment]
We were on 3.9.0 which had the openjdk:13 as base image but when we upgraded to 4.0.0 which is based on openjdk:11-jre-slim-buster we had some faillures (no `curl`, no `bash`)  
Point is that you can not rely on your base image (especially when it's a latest build) it may be susceptible to change. So there is no "known" version. Even liquibase 4.0.0 itself switched from  `openjdk:8-jre-alpine` to `openjdk:11-jre-slim-buster`

As for the LIQUIBASE_ENV environment variables I think it's better to wait until the support becomes official. Safety first! ;-)

Thnx, JG

**Comment by r2liquibase** [comment]
I agree @jgkoops . @nvoxland I'm going to wait until Docker makes this official. Cool?

**Comment by nvoxland** [comment]
As far as the changing base image, that should be changing less often now. By being based on 11 vs. 13, we are on a LTS version of liquibase so it can be more stable as a base. 

I took out the docker-specific environment support until we can support it in the main liquibase codebase. Hopefully that will be soon.

I also updated the readme.

I think this should be ready to merge now

**Review by r2liquibase — APPROVED** [review]

**Pull request merged**
