### PR TITLE
Reduce size of final image by removing apt caches

### PR DESCRIPTION
**Pull request by dhwanitsshah**

### CODE REVIEW

**Comment by r2liquibase** [comment]
Thanks @dhwanitsshah! What's the size savings we get with those changes? Also, can you rebase? Thanks!

**Comment by dhwanitsshah** [comment]
> Thanks @dhwanitsshah! What's the size savings we get with those changes? Also, can you rebase? Thanks!

That made a difference of about 17 MB

The first image(apt_clean tag)  is built after removing apt cache while the second image (without_apt_clean tag) was build without deleting apt cache.

REPOSITORY                                      TAG                                              IMAGE ID                CREATED                SIZE
liquibase/liquibase                             apt_clean                                     96b7f6c6bcd2       8 seconds ago       277MB
liquibase/liquibase                             without_apt_clean                       babc9ab43ccf       2 minutes ago        294MB

**Comment by r2liquibase** [comment]
Cool, @dhwanitsshah . Thanks a ton.

We've gotten a lot of heat from the users about the rate at which we are changing these images. Cool if we wait a while on this?

**Comment by dhwanitsshah** [comment]
Thanks @r2liquibase, sure we can wait for this until next release/update cycle.

**Comment by r2liquibase** [comment]
Hi, @dhwanitsshah ! Do you mind rebasing this. We made some changes in `main` that are causing a merge conflict. Thanks!

**Comment by dhwanitsshah** [comment]
@r2liquibase , @jgkoops  - I have rebased my branch with the new changes by resolving the conflicts.. could you please review and merge this  pull request?

**Review by jgkoops — APPROVED** [review]
OK w/ me

**Comment by dhwanitsshah** [comment]
Thanks @jgkoops

**Comment by dhwanitsshah** [comment]
@r2liquibase ,@jgkoops  -  Hi, may I know when this pull request will be merged ?

**Comment by r2liquibase** [comment]
Thank you @jgkoops  and @dhwanitsshah . We do have a small issue with the PR: Docker doesn't want us to use the CMD at the end to call --help by default. We're attempting to get this accepted as an official image from Docker Hub.

Here's the PR: https://github.com/docker-library/official-images/pull/8409.

**Comment by dhwanitsshah** [comment]
Great thanks @r2liquibase  for the update. Sure, will provide any refactor if need be once the thing gets finalized. :)

**Comment by r2liquibase** [comment]
I appreicate you @dhwanitsshah ! Feel free to comment on that PR and ask why they haven't accepted it!!!!

**Comment by dhwanitsshah** [comment]
Thanks @r2liquibase, have asked them if the changes are good to be merged.

**Comment by r2liquibase** [comment]
Thank you @dhwanitsshah !

**Comment by dhwanitsshah** [comment]
> Thank you @dhwanitsshah !

Thanks @r2liquibase  and @nvoxland  for PR review & merge! 👍

**Pull request merged**
