### PR TITLE
DAT-14759  DevOps :: Make Liquibase an official tagged image on Dockerhub

### PR DESCRIPTION
**Pull request by jandroav**
Changes from: https://github.com/docker-library/official-images/pull/8409#issuecomment-1885809753

chore(create-release.yml): add lpmVersion input with default value
chore(create-release.yml): add lpmVersion input with default value of "0.2.4"
fix(Dockerfile): remove unused TARGETARCH argument
fix(Dockerfile): remove unused TARGETARCH argument
fix(Dockerfile): update lpm download URL and add LPM_SHA256 verification
fix(Dockerfile): update lpm download URL and add LPM_SHA256 verification
fix(Dockerfile.alpine): remove unused TARGETARCH argument
fix(Dockerfile.alpine): remove unused TARGETARCH argument
fix(Dockerfile.alpine): update lpm download URL and add LPM_SHA256 verification
fix(Dockerfile.alpine): update lpm download URL and add LPM_SHA256 verification

### CODE REVIEW

**Comment by jnewton03** [comment]
@mcred these changes are to address Docker's comments..  Would like your thoughts

**Review by jnewton03 — APPROVED** [review]

**Comment by jnewton03** [comment]
@jandroav we should see why trivy failed too.

**Comment by jandroav** [comment]
> @jandroav we should see why trivy failed too.

`LPM_SHA` was empty and it will be filled for the first time once the release github action runs. I have added the current SHA for lpm and now it is working.

**Review by jnewton03 — APPROVED** [review]

**Review by mcred — APPROVED** [review]

**Comment by mcred** [comment]
@jnewton03 @jandroav looks good to me!

**Pull request merged**
